version: '2'
services:
  shoeshop-app:
    image: shoeshop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://shoeshop-mysql:3306/shoeshop?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8000:8000
  shoeshop-mysql:
    extends:
      file: mysql.yml
      service: shoeshop-mysql
